# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GRPC_Client.agent_host_info.agent_host_info_pb2 as agent__host__info__pb2


class HostAgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHostReport = channel.unary_unary(
                '/PIXIS.Grpc.Protos.HostAgentService/SendHostReport',
                request_serializer=agent__host__info__pb2.HostReportRequest.SerializeToString,
                response_deserializer=agent__host__info__pb2.HostReportReply.FromString,
                )


class HostAgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendHostReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHostReport': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHostReport,
                    request_deserializer=agent__host__info__pb2.HostReportRequest.FromString,
                    response_serializer=agent__host__info__pb2.HostReportReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PIXIS.Grpc.Protos.HostAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HostAgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendHostReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PIXIS.Grpc.Protos.HostAgentService/SendHostReport',
            agent__host__info__pb2.HostReportRequest.SerializeToString,
            agent__host__info__pb2.HostReportReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
